# Generated by Django 4.2.29 on 2026-03-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avafit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avafit',
            name='data_ultima_meta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avafit',
            name='melhor_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avafit',
            name='streak_atual',
            field=models.IntegerField(default=0),
        ),
    ]
