# Generated by Django 4.2.29 on 2026-03-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avafit', '0002_avafit_data_ultima_meta_avafit_melhor_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avafit',
            name='data_ultima_meta',
        ),
        migrations.RemoveField(
            model_name='avafit',
            name='melhor_streak',
        ),
        migrations.RemoveField(
            model_name='avafit',
            name='streak_atual',
        ),
    ]
