# Generated by Django 4.2.29 on 2026-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha AvaFit', max_length=100)),
                ('saude', models.IntegerField(default=100)),
                ('passos_hoje', models.IntegerField(default=0)),
                ('estado', models.CharField(default='Feliz', max_length=50)),
            ],
        ),
    ]
